name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
      id: go

    - name: Install ubuntu dependencies.
      run: sudo apt-get install libgl1-mesa-dev xorg-dev

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go mod download

    - name: Build example applications
      run: for i in examples/*; do go build "$i"/app.go; done;
